apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: fruits
    app.kubernetes.io/component: web
    app.kubernetes.io/instance: fruits
    app.kubernetes.io/name: fruits
    app.kubernetes.io/part-of: fruits
    app.openshift.io/runtime: java
  name: fruits
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fruits
  template:
    metadata:
      labels:
        app: fruits
    spec:
      containers:
      - name: fruits
        imagePullPolicy: Always
        #image: quay.io/siamaksade/fruits:latest
        image: image-registry.openshift-image-registry.svc:5000/<namespace>/<imagem>:<tag>
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 45
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 45
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5