apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-access
  namespace: demo-pipelines
subjects:
- kind: ServiceAccount
  name: argocd-application-controller
  namespace: demo-pipelines
roleRef:
  kind: Role
  name: argocd-manager
  apiGroup: rbac.authorization.k8s.io