apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-activemqartemises-manager
  namespace: amq
rules:
- apiGroups: ["broker.amq.io"]
  resources: ["activemqartemises","activemqartemisaddresses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]